journal/urls.py
from django.urls import path
from . import views

app_name = "journal"

urlpatterns = [
    path("", views.JournalBookList.as_view(), name="index"),
    path("<int:pk>", views.JournalDetailView.as_view(), name="detail"),
    path("<int:pk>/update", views.update_journal_book, name="update"),
    path("<int:pk>/delete", views.delete_journal_book, name="delete"),
    path("create", views.create_journal_book, name="create"),
    path("entries/<int:pk>", views.JournalEntryDetailView.as_view(), name='entry_detail'),
    path("entries/create/<int:pk>", views.create_entry, name='entry_create'),
    path("entries/<int:pk>/update", views.update_journal_entry, name='entry_update'),
    path("entries/<int:pk>/delete", views.delete_journal_entry, name='entry_delete'),
]

journalapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('journal.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
]

users/urls.py
from django.urls import path, include
from . import views

# app_name='users'

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('register/', views.register, name='register'),
]

journal/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class JournalBook(models.Model):
    user = models.ForeignKey(User, related_name="user_journalbooks", on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = "Journal Books"

    def __str__(self):
        return self.title

class JournalEntry(models.Model):
    user = models.ForeignKey(User, related_name="user_journalentries", on_delete=models.CASCADE)
    journalbook = models.ForeignKey(JournalBook, related_name="journalbook_entries", on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    body = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = "Journal Entries"

    def __str__(self):
        return self.title

users/models.py
from django.db import models

journal/forms.py
from django.forms import ModelForm
from .models import JournalBook

class JournalBookForm(ModelForm):
    class Meta:
        model = JournalBook
        fields = ['title','description',]

users/forms.py
from django.contrib.auth.forms import UserCreationForm

class CustomUserCreateForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        fields = UserCreationForm.Meta.fields + ("email",)

journal/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from django.views.generic import ListView, DetailView
from .models import *
from django.contrib.auth.decorators import login_required
from .forms import JournalBookForm
from django.db import transaction
# Create your views here.
def index(request):
    n = range(1,12)
    journals = request.user.user_journalbooks.all()
    context = { 
        "n" : n,
        "journals" : journals 
    }
    return render(request, "journal/index.html", context=context)

class JournalBookList(LoginRequiredMixin, ListView):

    model = JournalBook
    context_object_name = 'journals'
    template_name = "journal/index.html"

    def get_queryset(self):
        return self.request.user.user_journalbooks.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

class JournalDetailView(LoginRequiredMixin, DetailView):
    model = JournalBook
    context_object_name = 'journal'




class JournalEntryDetailView(LoginRequiredMixin, DetailView):
    model = JournalEntry
    context_object_name = 'entry'


"""
Function-based Views
We will convert them to class-based views soon.
"""
@login_required()
@transaction.atomic()
def create_journal_book(request):
    form = JournalBookForm()

    if request.method == 'GET':
        return render(request, "journal/journalbook_create.html", { "form" : form })
    elif request.method == 'POST':
        form = JournalBookForm(request.POST)
        if form.is_valid():
            journalbook = form.save(commit=False)
            journalbook.user = request.user
            journalbook.save()
        return redirect(reverse("journal:detail", args=(journalbook.id,)))

@login_required()
@transaction.atomic()
def update_journal_book(request, pk):
    journal = request.user.user_journalbooks.get(pk=pk)
    form = JournalBookForm(instance=journal)

    if request.method == 'GET':
        return render(request, "journal/journalbook_update.html", { "form" : form })
    elif request.method == 'POST':
        form = JournalBookForm(request.POST, instance=journal)

        if form.is_valid():
            journalbook = form.save()
        return redirect(reverse("journal:detail", args=(journalbook.id,)))

@login_required()
def delete_journal_book(request, pk):
    journal = request.user.user_journalbooks.get(pk=pk)
    journal.delete()
    return redirect(reverse("journal:index"))

@login_required()
@transaction.atomic()
def create_entry(request, pk):
    journal = request.user.user_journalbooks.get(pk=pk)
    if request.method == 'GET':
        context = {
            "journal" : journal,
        }
        return render(request, "journal/journalentry_create.html", context)
    elif request.method == "POST":
        entry = JournalEntry(
            title=request.POST['title'],
            body=request.POST['text_body'],
            journalbook=journal,
            user=request.user
        )
        entry.save()
        return redirect(reverse("journal:entry_detail", args=(entry.id,)))


@login_required()
def update_journal_entry(request, pk):
    entry = request.user.user_journalentries.get(pk=pk)

    if request.method == 'POST':
        entry.title = request.POST['title']
        entry.body = request.POST.get('text_body')
        entry.save()
        
    return redirect(reverse("journal:entry_detail", args=(entry.id,)))

@login_required()
def delete_journal_entry(request, pk):
    entry = request.user.user_journalentries.get(pk=pk)
    journal = request.user.user_journalbooks.get(pk=entry.journalbook.id)
    entry.delete()
    return redirect(reverse("journal:detail", args=(journal.id,)))

users/views.py
from django.shortcuts import render
from django.shortcuts import redirect, render
from django.urls import reverse
from users.forms import CustomUserCreateForm

# Create your views here.
def dashboard(request):
    return render(request, "users/dashboard.html")

def register(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect(reverse("users:dashboard"))
    elif request.method == 'GET':
        return render(request, "registration/register.html",{ "form" : CustomUserCreateForm})

journal/templates/journal/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gratitude Journal</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
</head>
<body>
    <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="{% url 'journal:index' %}">Gratitude Journal</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'journal:index' %}">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'dashboard' %}">Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container" style="padding-top: 75px;">
        {% block content %}{% endblock content %}
    </div>

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
    {% block footer_scripts %}{% endblock footer_scripts %}
</body>
</html>

journal/templates/journal/index.html
{% extends "journal/base.html" %}

{% block content %}

<div class="d-block pb-3 text-right">
    <a href="{% url 'journal:create' %}" class="btn btn-success">Create New Journal</a>
</div>

<div class="row">
    {% for journal in journals %}
        {% if forloop.counter > 3 %}
            <div class="col-md-4 mt-3">
        {% else %}
            <div class="col-md-4">
        {% endif %}
            <div class="card">
                <div class="card-body">
                    <a href="{% url 'journal:detail' journal.id %}"><h3>{{ journal.title }}</h3></a>
                    <p class="text-muted">{{ journal.description }}</p>
                </div>
            </div>
        </div>
    {% endfor %}
</div>

{% endblock content %}

journal/templates/journal/journalbook_create.html
{% extends "journal/base.html" %}

{% load crispy_forms_tags %}

{% block content %}

<div class="row">
    <div class="col-md-6">
        <h4>Create A New Journal Book</h4>
        <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-success">Submit</button>
        </form>
    </div>
</div>

{% endblock content %}

journal/templates/journal/journalbook_detail.html
{% extends "journal/base.html" %}

{% block content %}

{% load humanize %}

<div class="row">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <h3 class="mb-0">{{ journal.title }}</h3>
            </div>
            <div class="card-body">
                <pre>{{ journal.description }}</pre>

                <span class="d-block">
                    <span class="badge badge-secondary">Created At: {{ journal.created_at|naturaltime }}</span>
                    <span class="badge badge-primary">Last Updated: {{ journal.created_at|naturaltime }}</span>
                </span>
            </div>
            <div class="card-footer">
                <a href="{% url 'journal:update' journal.id %}" class="btn btn-primary">Edit</a>
                <a href="{% url 'journal:delete' journal.id %}" class="btn btn-danger">Delete</a>
            </div>
        </div>
    </div>

    <div class="col-md-6">
        <div class="list-group">
            {% for entry in journal.journalbook_entries.all %}
                <a href="{% url 'journal:entry_detail' entry.id %}" class="list-group-item list-group-item-action">
                    <div class="d-flex w-100 justify-content-between">
                        <h5 class="mb-0">{{ entry.title }}</h5>
                        <small class="align-self-center">{{ entry.updated_at|naturaltime }}</small>
                    </div>
                </a>
            {% endfor %}

        </div>
        
        <a href="{% url 'journal:entry_create' journal.id %}" class="btn btn-success mt-3">Add New Entry</a>
    </div>
</div>

{% endblock content %}

journal/templates/journal/journalbook_update.html
{% extends "journal/base.html" %}

{% load crispy_forms_tags %}

{% block content %}

<div class="row">
    <div class="col-md-6">
        <h4>Edit Journal Book <span class="badge badge-primary">{{ form.instance.title }}</span></h4>
        <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-primary">Update</button>
        </form>
    </div>
</div>

{% endblock content %}

journal/templates/journal/journalentry_create.html
{% extends "journal/base.html" %}

{% block content %}

<div class="row">
    <div class="col-md-12">

        <h4>Create A New Journal Entry <span class="badge badge-primary">{{ journal.title }}</span></h4>
        <hr>

        <form action="{% url 'journal:entry_create' journal.id %}" method="POST">

        {% csrf_token %}

        <h3 class="display-4">
            <input type="text" name="title" placeholder="Entry Title is required ..." value="{{ entry.title }}" style="border: 0; width: 100%" required>
        </h3>

        <textarea name="text_body" id="myID">{{ entry.body }}</textarea>

        <input type="hidden" value="{{ entry.journalbook.id }}" name="journalbook" />

        <button class="btn btn-success">Create</button>

        </form>
    </div>
</div>

{% endblock content %}

{% block footer_scripts %}
<script>
    var simplemde = new SimpleMDE({ 
        element: document.getElementById("myID"),
        forceSync: true 
    });
</script>
{% endblock footer_scripts %}

journal/templates/journal/journalentry_detail.html
{% extends "journal/base.html" %}

{% load humanize %}

{% block content %}

<form action="{% url 'journal:entry_update' entry.id %}" method="POST">

{% csrf_token %}

<h3 class="display-3">
    <input type="text" name="title" placeholder="Entry Title is required ..." value="{{ entry.title }}" style="border: 0; width: 100%">
</h3>

<textarea name="text_body" id="myID">{{ entry.body }}</textarea>

<input type="hidden" value="{{ entry.journalbook.id }}" name="journalbook" />

<a href="{% url 'journal:detail' entry.journalbook.id %}" class="btn btn-success">&larr; Go back to Journal</a>

<button class="btn btn-primary">Update</button>
<a href="{% url 'journal:entry_delete' entry.id %}" class="btn btn-danger">Delete</a>

</form>

{% endblock content %}

{% block footer_scripts %}
<script>
    var simplemde = new SimpleMDE({ 
        element: document.getElementById("myID"),
        forceSync: true 
    });
</script>
{% endblock footer_scripts %}

users/templates/users/base.html
{% extends "journal/base.html" %}

{% block content %}
    <h1>Welcome to User Management Dashboard</h1>
    <hr>
{% endblock content %}

users/templates/users/dashboard.html
{% extends "users/base.html" %}

{% block content %}

<h4>Welcome, {{ user.username|default:'Guest' }}</h4>

<div class="mt-3">
    {% if user.is_authenticated %}
        <a href="{% url 'logout' %}" class="btn btn-danger">Logout</a>
        <a href="{% url 'password_change' %}" class="btn btn-warning">Change password</a>
    {% else %}
        <a href="{% url 'login' %}" class="btn btn-success">Login</a>
    {% endif %}
</div>
{% endblock content %}